### ISSUE TITLE
Add build stage to Dockerfile

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/sustainability-dashboard#112]
Assets need to be build with node before creating the docker image. Add a build stage to Dockerfile that builds the assets and copy the result to the final image.

- [ ] Add build stage to Dockerfile
- [ ] Remove build step from GitHub action

Example:

```dockerfile
FROM node:19-buster-slim as build

COPY . /build
RUN cd /build && npm ci && npm run all

FROM caddy:2.6.2

...

COPY --from=build /build/site /usr/share/caddy

...
```

**Comment by phish108** [comment]
The build stage is stretching the build time for the github action. It is more useful to run the build externally and copy the result into the fresh container as it is implemented in the action file. 

This is a bit more cumbersome for local development, but significantly speeds up the deployment process.

**Comment by stlozhaw** [comment]
What do you think about adding another Dockerfile with the build stage? That one could be used for local development or referenced by integration-test repo for local builds.
