### ISSUE TITLE
display query errors not as tooltips

### ISSUE THREAD

**Issue by phish108** [sustainability-zhaw/sustainability-dashboard#58]
Problem: the tooltip overlays with the query terms. A user cannot see the information that relates to the message :(

Background: If a user makes a query error, the system will turn the input field in the query box to color "red"/"danger" and display an error information as a tooltip. 

This is a problem because the tooltip will overlap with one or more query terms in the box below. The following screen shot illustrates this. 

<img width="1514" alt="Bildschirmfoto 2023-02-21 um 21 31 43" src="https://user-images.githubusercontent.com/866505/220451885-dd13a6f4-a9f6-4235-8ab0-9a93049ec41f.png">

It would be nicer to use the space in the query box  for the message. E.g. using a red/danger overlay on top of the "Press Return to add". button. 

It would be also useful, if the offending term is highlighted.

**Comment by GeroVanMi** [comment]
@phish108 

Is the following screenshot the problem that is supposed to be fixed? 
![image](https://user-images.githubusercontent.com/39983753/220441043-af584585-83e9-45bf-b514-5e224fd73a76.png)

**Comment by phish108** [comment]
I updated the issue report above and added a screenshot. This shows the problem very clearly. 

A long query is a problem by itself. However it seems that very long queries generate problems. 

I am a bit worried that your screenshot does not show the icons properly. Did you run `npm install` before you started the integration testing?
