### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by GeroVanMi** [sustainability-zhaw/sustainability-dashboard#95]
During the setup I encountered the following issues that were not immediately obvious from ReadMe file. 
With your permission @phish108 I would like to add documentation for them, so that when we or someone new has to install the project on a new machine, they don't run into them as well. 

- [x] Install npm packages with `npm ci`
- [x] Download the bootstrap `.min.js` file into the `/site/assets/js/` folder. (Reference: https://getbootstrap.com/) (Find the CDN link and download the file that is linked on the CDN) 
- [x] Download the popper `.min.js` file into the `site/assets/js/` folder. (Reference: https://popper.js.org/)  
- [x] Download the bootstrap icons font. (Reference: @phish108 **could you provide me with the link to the fonts? I was unable to find the woff files online on my own**) 
- [x]  Mention that it is necessary to create the ad_config.env file in the ReadMe and link to [.env-example](https://github.com/sustainability-zhaw/ad-resolver/blob/main/.env-example)

**Comment by phish108** [comment]
All dependencies are automatically installed on your system via `npm`. 

you need to run to following on a posix compliant shell. 

```bash
npm ci && npm run all
```

On Windows this might be two separate steps. 

```bash
npm ci 
npm run all
```

**Comment by phish108** [comment]
Documentation fixed with commit [b1d988f](https://github.com/sustainability-zhaw/sustainability-dashboard/commit/b1d988fbddf6562cb748f58d21f5e8053482d737)
